import javax.swing.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.JFileChooser;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Rahmat
 */
public class PenghitungKataFrame extends javax.swing.JFrame {

    private String kata;
    

    /**
     * Creates new form PenghitungKataFrame
     */
    public PenghitungKataFrame() {
        initComponents();
         // Menambahkan DocumentListener pada textArea
        textArea.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) {
                updateHasil(); // Update hasil saat teks ditambah
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                updateHasil(); // Update hasil saat teks dihapus
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                updateHasil(); // Update hasil saat format teks berubah
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        labelKata = new javax.swing.JLabel();
        labelKalimat = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textArea = new javax.swing.JTextArea();
        btnHitung = new javax.swing.JButton();
        labelKarakterTotalNonSpasi = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        labelParagraf = new javax.swing.JLabel();
        textFieldCari = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btnCari = new javax.swing.JButton();
        btnSimpan = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labelKata.setText("jumlah kata");

        labelKalimat.setText("Jumlah Kalimat ");

        textArea.setColumns(20);
        textArea.setRows(5);
        jScrollPane1.setViewportView(textArea);

        btnHitung.setText("Hitung");
        btnHitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHitungActionPerformed(evt);
            }
        });

        labelKarakterTotalNonSpasi.setText("Jumlah Karakter");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Aplikasi Penghitung Kata");

        labelParagraf.setText("Jumlah Paragraf");

        textFieldCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldCariActionPerformed(evt);
            }
        });

        jLabel2.setText("Pencarian Kata : ");

        btnCari.setText("Cari");
        btnCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCariActionPerformed(evt);
            }
        });

        btnSimpan.setText("Simpan");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(177, 177, 177))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelKata, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelKalimat, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelKarakterTotalNonSpasi, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelParagraf, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnCari)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(textFieldCari, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel2))))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(149, 149, 149)
                        .addComponent(btnHitung)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSimpan)))
                .addContainerGap(77, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(53, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(textFieldCari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnCari))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnHitung)
                    .addComponent(btnSimpan))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelKata)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelKarakterTotalNonSpasi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelKalimat)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelParagraf)
                .addGap(57, 57, 57))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnHitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHitungActionPerformed
        updateHasil();
    }//GEN-LAST:event_btnHitungActionPerformed

    private void textFieldCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldCariActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldCariActionPerformed

    private void btnCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariActionPerformed
        btnCariActionPerformed();
    }//GEN-LAST:event_btnCariActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        btnSimpanActionPerformed();
    }//GEN-LAST:event_btnSimpanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PenghitungKataFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PenghitungKataFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PenghitungKataFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PenghitungKataFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PenghitungKataFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCari;
    private javax.swing.JButton btnHitung;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelKalimat;
    private javax.swing.JLabel labelKarakterTotalNonSpasi;
    private javax.swing.JLabel labelKata;
    private javax.swing.JLabel labelParagraf;
    private javax.swing.JTextArea textArea;
    private javax.swing.JTextField textFieldCari;
    // End of variables declaration//GEN-END:variables

    private void updateHasil() {
    String teks = textArea.getText();

    // Menghitung jumlah kata
    String[] kata = teks.trim().isEmpty() ? new String[0] : teks.trim().split("\\s+");
    int jumlahKata = kata.length;

    // Menghitung jumlah karakter (total dan non-spasi)
    int jumlahKarakterTotal = teks.length();
    int jumlahKarakterNonSpasi = teks.replace(" ", "").length();

    // Menghitung jumlah kalimat
    String[] kalimat = teks.trim().isEmpty() ? new String[0] : teks.split("[.!?]+");
    int jumlahKalimat = kalimat.length;

    // Menghitung jumlah paragraf
    String[] paragraf = teks.split("\n+"); // Menggunakan \n untuk memisahkan paragraf
    int jumlahParagraf = paragraf.length;

    // Tampilkan hasil pada label
    labelKata.setText("Jumlah Kata: " + jumlahKata);
    
    // Gabungkan jumlah karakter total dan non-spasi dalam satu label
    labelKarakterTotalNonSpasi.setText("Jumlah Karakter (Total): " + jumlahKarakterTotal + " | (Non-Spasi): " + jumlahKarakterNonSpasi);
    
    labelKalimat.setText("Jumlah Kalimat: " + jumlahKalimat);
    
    // Menampilkan jumlah paragraf
    labelParagraf.setText("Jumlah Paragraf: " + jumlahParagraf);  // Asumsikan Anda menambahkan labelParagraf
    }

    private void btnCariActionPerformed() {
      String teks = textArea.getText(); // Ambil teks dari JTextArea
    String kataCari = textFieldCari.getText().trim(); // Ambil kata dari JTextField dan hilangkan spasi ekstra

    // Pastikan kata yang dicari tidak kosong
    if (!kataCari.isEmpty()) {
        // Debugging: Cetak teks dan kata yang dicari
        System.out.println("Teks: " + teks);
        System.out.println("Kata Cari: " + kataCari);

        // Panggil fungsi hitungKata untuk mencari kata
        int jumlahDitemukan = hitungKata(teks, kataCari); 

        // Tampilkan hasil pencarian
        if (jumlahDitemukan > 0) {
            JOptionPane.showMessageDialog(this, "Kata '" + kataCari + "' ditemukan " + jumlahDitemukan + " kali.");
        } else {
            JOptionPane.showMessageDialog(this, "Kata '" + kataCari + "' tidak ditemukan.");
        }
    } else {
        JOptionPane.showMessageDialog(this, "Masukkan kata yang ingin dicari.");
    }
    }

    private int hitungKata(String teks, String kataCari) {
      int count = 0;
    int index = 0;

    // Pastikan kata yang dicari tidak kosong
    if (kataCari != null && !kataCari.isEmpty()) {
        // Menggunakan toLowerCase() untuk mengabaikan kapitalisasi
        teks = teks.toLowerCase();
        kataCari = kataCari.toLowerCase();

        // Debugging: Cek teks setelah mengubah ke lowercase
        System.out.println("Teks (lowercase): " + teks);
        System.out.println("Kata Cari (lowercase): " + kataCari);

        // Loop untuk menemukan semua kemunculan kata
        while ((index = teks.indexOf(kataCari, index)) != -1) {
            count++;   // Tambah hitungan setiap kali ditemukan
            index += kataCari.length();  // Pindah ke indeks setelah kata yang ditemukan
        }
    }
    return count;
}

    private void btnSimpanActionPerformed() {
        // Ambil teks dari JTextArea
        String teks = textArea.getText();

        // Ambil hasil perhitungan
        String hasil = "Jumlah Kata: " + labelKata.getText() + "\n" +
                       "Jumlah Karakter (Total): " + labelKarakterTotalNonSpasi.getText() + "\n" +
                       "Jumlah Kalimat: " + labelKalimat.getText() + "\n" +
                       "Jumlah Paragraf: " + labelParagraf.getText();

        // Gabungkan teks dan hasil perhitungan
        String contentToSave = teks + "\n\n" + hasil;

        // Buka dialog untuk memilih lokasi file
        JFileChooser fileChooser = new JFileChooser();
        int option = fileChooser.showSaveDialog(this);
        if (option == JFileChooser.APPROVE_OPTION) {
            File fileToSave = fileChooser.getSelectedFile();
            try {
                // Simpan file
                BufferedWriter writer = new BufferedWriter(new FileWriter(fileToSave));
                writer.write(contentToSave);  // Menulis konten ke file
                writer.close();
                JOptionPane.showMessageDialog(this, "Teks dan hasil perhitungan telah disimpan.");
            } catch (IOException e) {
                JOptionPane.showMessageDialog(this, "Terjadi kesalahan saat menyimpan file: " + e.getMessage());
            }
        }
    }
}
